### ISSUE TITLE
Support creation/deletion of application-scoped namespace

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#4742]
## Overview of feature request

We’ve added support for an application namespace in the application data model and frontend controller so the next step is to create the Kubernetes namespace. Along with this, there should be support for application namespace deletion. There’s a few options for this that could work:
1. Create/delete a Kubernetes namespace in the frontend controller
2. Create/delete a Kubernetes namespace in the backend controller 

I think option 2 in the backend controller would make the most sense for this feature since these actions might need to be handle asynchronously. Deleting the `radius-system` namespace in Kubernetes takes about a minute to delete both the namespace and its resources, but that could easily increase if more resources are deployed in a given app namespace. 

PUT/DELETE requests for applications are sync requests right now so these would need to be updated to async. Additionally, we would need to add new deployment process renders for application resources.   

## Tasks

- [ ] Discuss options on how to handle application namespace creation/deletion
- [ ] Update PUT/DELETE requests in applications API from sync to async
- [ ] Add support for creation/deletion of application namespace
- [ ] Add application resource renders
- [ ] Add unit-test for application resource renders

## Acceptance criteria

- [ ] As an user, I can create and delete namespaces at application level

## Additional context

[AB#5180](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5180)

**Comment by nicolejms** [comment]
very old so closing
