### ISSUE TITLE
Store edge version rad cli and bicep binary in GHCR

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#6295]
## Problem

Once we move blob storage to GitHub Release, it is hard to manage edge version rad cli. The proposal is to use OCI-compliant GHCR for storing edge version rad cli.

## Tasks
* [x] Publish bicep to GHCR using oras client (ensure that we publish multiple arch binaries to GHCR).
* [x] Enable rad cli to download bicep from GHCR (only edge)
* [x] Publish rad cli to GHCR using oras client. 
* [ ] Update docs to use oras client to download edge version of rad cli.

[AB#9834](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9834)

**Comment by AaronCrawfis** [comment]
There are still some items in the description to do

**Comment by rynowak** [comment]
@AaronCrawfis - are the checkboxes in the description up-to-date? What's the user impact of the gaps? 

Knowing what users are blocked from doing will help us know how to prioritize.

**Comment by shalabhms** [comment]
triage: There are still places in the code where GHCR is not getting consumed , still the old way of blob store. @willdavsmith is working on it to complete the story.

**Comment by AaronCrawfis** [comment]
Reopening as there are still tasks to complete in the description

**Comment by AaronCrawfis** [comment]
Docs have been updated
