### ISSUE TITLE
Model and deploy 10 most commonly used AWS services via Radius

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/radius#6380]
## Overview of the feature request
This feature is to validate the modeling and deployment of the most commonly used AWS services via Radius. This is an exercise to learn the unknowns in the AWS space and figure out the plan for Radius to fill in gaps via features and documentation

### Phase 1

- [x] radius-project/radius#4106
- [x] radius-project/radius#4107
- [x] radius-project/radius#4108

**Comment by nicolejms** [comment]
closing old issues
