### ISSUE TITLE
Design on streamlining the usage of AWS VPC in Radius

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/radius#6381]
## Summary
Amazon Virtual Private Cloud (Amazon VPC) enables you to launch AWS resources into a virtual network that you've defined. This virtual network closely resembles a traditional network that you'd operate in your own data center, with the benefits of using the scalable infrastructure of AWS. 

VPC’s are a central concept in AWS and by default a VPC is created for you when an AWS account is created. Most of the resources in AWS are launched in a VPC. If you don’t specify a custom VPC, it gets created in the default VPC

## Customer Workflow
Let's navigate through this with a customer workflow
As an Infrastructure Operator, 
- I create VPC, subnets, IAM roles, and an EKS cluster all outside of Radius 
- I install the Radius control plane via Radius CLI/Helm chart 
- I create a Radius environment with the infrastructure services via Radius CLI / Bicep

As a Developer,
- I create my app definitions in Bicep with Radius and AWS app resources. To know what VPC's to use or what resources created in the VPC need to be referenced, the Operator should give the developer this information, this could probably be captured as part of the recipes

## Major areas of investment 

**- Enable infrastructure operators to declare VPC when creating a Radius environment with AWS cloud provider** 
Recipes look like a place to add this information. Understand recipes and how VPC's could be added to it. Need to explore this if this is just going to be content writing as recipes functionality is built out 

- [x] project-radius/radius#5351

**- Enable developers to model and route resources to subnets in a VPC when modeling application definition in Bicep** 

_As is experience_   
As part of the AWS quickstart, we do this today by creating a subnet group from the EKS cluster subnet id and using the subnet group to deploy the memory DB but need to streamline this from the context of VPC info being available during app modelling

_To be experience_ 

-As a developer, I can use connector recipes to model AWS resources in my app without having to specify VPC config
-As a developer, I can model an AWS resource by using the VPC or network config created by my infrastructure operator
- [x] project-radius/radius#4094 
      - need an application model that deploys resources to separate VPC'S that need to be peered to showcase the concept of VPC (can leverage AWS examples/ reference architectures)
       eg - there might be an application that has the front end exposed to the internet and the backend not publicly accessible. Help developers model an app definition to route resources to public and private subnets in a VPC based on the application architecture
        

- [x] project-radius/radius#4095
        - We would need a reference application from AWS radified and documented here -https://edge.radapp.dev/getting-started/reference-apps/
        - Initially learn and identify the gaps that exist today and figure out a plan on how Radius can fill in the gaps
        - Understand how the existing reference apps are picked. Reach out to SA's from Azure to pick an AWS example similar to Azure (Maybe Ryan Sweet or SA's from out preview dicussion can help us here) 
        - This brings a conviction to the customers that we can make any application work in Radius and that we are investing to make AWS work
        - Reference resources could be potentially explored too  (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w2ab1c33c58c13c15)
         

[AB#4201](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4201)

**Comment by nicolejms** [comment]
very old so closing
